version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: trading_app_backend
    ports:
      - "8080:8080"
    environment:
      # Use environment variables for sensitive data
      - DATABASE_URL=postgresql://user:password@db:5432/trading_signals
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: trading_app_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    container_name: trading_app_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trading_signals
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d trading_signals"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: